collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/img"
    values:
      image: true

url: codybenlewis.github.io
baseurl: /CBL-Personal-Website
