defaults:

  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "note"
      permalink: notes/:slug/

collections:
  projects:
    output: true
    permalink: :collection/:name/
