collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/images"
    values:
      image: true

url: http://codybenlewis.github.io
baseurl: /CBL-Personal-Website
